/*
 * JIFConfiguracion.java
 *
 * Created on 6 de enero de 2010, 0:06
 */
package Interficie;

import Aplicacion.ControladorAplicacion;
import java.awt.Dimension;
import javax.swing.JFileChooser;
import javax.swing.JSlider;

/**
 *
 * @author  Daniri
 */
public class JIFConfiguracion extends javax.swing.JInternalFrame {

    private ControladorAplicacion crtlApp;

    /** Creates new form JIFConfiguracion */
    public JIFConfiguracion() {
        initComponents();
        try {
            crtlApp = ControladorAplicacion.getInstancia();
        } catch (Exception e) {
            JDExcepcion jDExcepcion = new JDExcepcion();
            jDExcepcion.setPreferredSize(new Dimension(564, 230));
            jDExcepcion.pack();
            jDExcepcion.setLocationRelativeTo(this);
            jDExcepcion.setText(e.getMessage());
            jDExcepcion.setVisible(true);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        chkBayesNet = new javax.swing.JRadioButton();
        cHKNaiveBayes = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cHKJ48 = new javax.swing.JRadioButton();
        cHKJ48Graft = new javax.swing.JRadioButton();
        cHKNBTree = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sIzquierda = new JSlider();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        sDerecha = new JSlider();
        jLabel10 = new javax.swing.JLabel();
        lblIzquierda = new javax.swing.JLabel();
        lblDerecha = new javax.swing.JLabel();
        ChkBayedNetTAN = new javax.swing.JRadioButton();
        ChkCrossValidation = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        ChkUsarEscenaroPredefinido = new javax.swing.JCheckBox();
        chkUsarEscenarioAleatorio = new javax.swing.JCheckBox();
        chkActivarRelentizacion = new javax.swing.JCheckBox();
        txtRiempoRelentizacion = new javax.swing.JTextField();
        lblTiempoEntrefps = new javax.swing.JLabel();
        lblTiempoEnMs = new javax.swing.JLabel();
        txtSeed = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jBCancelar = new javax.swing.JButton();
        jBAceptar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtRutaFicheros = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtTiempoGrabacion = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtTiempoGrabacionEstadisticas = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Configuración de la aplicación");
        setMinimumSize(new Dimension(905, 792));
        setPreferredSize(new Dimension(905, 792));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Weka"));

        jLabel1.setText("Clasificador por defecto:");

        buttonGroup1.add(chkBayesNet);
        chkBayesNet.setText("BayesNet");

        buttonGroup1.add(cHKNaiveBayes);
        cHKNaiveBayes.setText("NaiveBayes");

        jLabel2.setText("Bayes");

        jLabel3.setText("Arboles");

        buttonGroup1.add(cHKJ48);
        cHKJ48.setText("J48");

        buttonGroup1.add(cHKJ48Graft);
        cHKJ48Graft.setText("J48Graft");

        buttonGroup1.add(cHKNBTree);
        cHKNBTree.setText("NBTree");

        jLabel4.setText("Peso sobre la distribución");

        jLabel5.setText("Izquierda");

        jLabel6.setText("0");

        jLabel7.setText("1");

        sIzquierda.setMajorTickSpacing(10);
        sIzquierda.setPaintTicks(true);
        sIzquierda.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderIzquierdaListener(evt);
            }
        });

        jLabel8.setText("Derecha");

        jLabel9.setText("0");

        sDerecha.setMajorTickSpacing(10);
        sDerecha.setPaintTicks(true);
        sDerecha.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                DerechaStateChange(evt);
            }
        });

        jLabel10.setText("1");

        lblIzquierda.setText("jLabel11");

        lblDerecha.setText("jLabel12");

        buttonGroup1.add(ChkBayedNetTAN);
        ChkBayedNetTAN.setText("BayesNet (TAN)");

        ChkCrossValidation.setText("Cross Validation");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDerecha)
                        .addGap(108, 108, 108))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cHKNaiveBayes)
                                    .addComponent(chkBayesNet)
                                    .addComponent(jLabel2)
                                    .addComponent(ChkBayedNetTAN))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cHKNBTree)
                                    .addComponent(cHKJ48)
                                    .addComponent(jLabel3)
                                    .addComponent(cHKJ48Graft)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(ChkCrossValidation)))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                                .addComponent(lblIzquierda)
                                .addGap(109, 109, 109))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(210, 210, 210)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sIzquierda, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)))))
                .addGap(61, 61, 61))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(284, 284, 284)
                .addComponent(jLabel4)
                .addContainerGap(302, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(sIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIzquierda))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cHKJ48)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cHKJ48Graft)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cHKNBTree))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chkBayesNet)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cHKNaiveBayes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ChkBayedNetTAN)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDerecha))
                    .addComponent(ChkCrossValidation))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Escenario"));

        buttonGroup2.add(ChkUsarEscenaroPredefinido);
        ChkUsarEscenaroPredefinido.setText("Usar escenario predefinido");

        buttonGroup2.add(chkUsarEscenarioAleatorio);
        chkUsarEscenarioAleatorio.setText("Usar escenario aleatorio");

        chkActivarRelentizacion.setText("Activar ralentización");
        chkActivarRelentizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checked(evt);
            }
        });

        txtRiempoRelentizacion.setText("0");
        txtRiempoRelentizacion.setEnabled(false);

        lblTiempoEntrefps.setText("Tiempo entre 2 frames por segundo");
        lblTiempoEntrefps.setEnabled(false);

        lblTiempoEnMs.setText("(En milisegundos)");
        lblTiempoEnMs.setEnabled(false);

        jLabel20.setText("Seed de aparición de vehículos");

        jLabel21.setText("0 Para Aleatorio");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSeed, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21))
                    .addComponent(chkActivarRelentizacion)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ChkUsarEscenaroPredefinido)
                                .addGap(42, 42, 42))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblTiempoEntrefps)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtRiempoRelentizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTiempoEnMs))
                            .addComponent(chkUsarEscenarioAleatorio))))
                .addContainerGap(438, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChkUsarEscenaroPredefinido)
                    .addComponent(chkUsarEscenarioAleatorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkActivarRelentizacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTiempoEnMs)
                    .addComponent(txtRiempoRelentizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTiempoEntrefps))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20))
                .addContainerGap())
        );

        jLabel21.getAccessibleContext().setAccessibleName("0 Para Aleatório");

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jBAceptar.setText("Aceptar");
        jBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Avanzadas"));

        jLabel15.setText("Ruta para la grabación de los ficheros");

        jLabel17.setText("Tiempo de grabación a disco de ficheros temporales");

        jLabel18.setText("Cada");

        jLabel19.setText("Segundos");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/carpeta.png"))); // NOI18N
        jButton1.setText("Examinar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel22.setText("Tiempo de grabación a disco de ficheros temporales de estadísticas");

        jLabel23.setText("Cada");

        jLabel24.setText("Segundos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17)
                            .addComponent(jLabel22)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(txtRutaFicheros, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTiempoGrabacion, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTiempoGrabacionEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRutaFicheros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(27, 27, 27)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtTiempoGrabacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtTiempoGrabacionEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
// TODO add your handling code here:
    this.setVisible(false);
}//GEN-LAST:event_jBCancelarActionPerformed

    public void setVisible(boolean visible) {
        if (!super.isVisible()) {
            try {
                String[] config = crtlApp.ObtenerConfiguracion();
                /*0  clasificador = "J48";
                1  rutaGrabacionFicheros = "C:/ProyectoFinalCarreraDani/";
                2  pesoDistIzquierda = 0;
                3  pesoDistDerecha = 0;
                4  escenarioPredifinido = false;
                5  relentizacion = 0;    */
                if (config[0].equalsIgnoreCase("bayesnet")) {
                    chkBayesNet.setSelected(true);
                } else {
                    if (config[0].equalsIgnoreCase("naivebayes")) {
                        cHKNaiveBayes.setSelected(true);
                    } else {
                        if (config[0].equalsIgnoreCase("j48")) {
                            cHKJ48.setSelected(true);
                        } else {
                            if (config[0].equalsIgnoreCase("j48graft")) {
                                cHKJ48Graft.setSelected(true);
                            } else {
                                if (config[0].equalsIgnoreCase("nbtree")) {
                                    cHKNBTree.setSelected(true);
                                } else {
                                    if (config[0].equalsIgnoreCase("bayesnetTAN")) {
                                        ChkBayedNetTAN.setSelected(true);
                                    }
                                }
                            }
                        }
                    }
                }
                txtRutaFicheros.setText(config[1]);
                sIzquierda.setValue((int) (Double.parseDouble(config[2]) * 100));

                sDerecha.setValue((int) (Double.parseDouble(config[3]) * 100));

                lblIzquierda.setText("" + config[2]);
                lblDerecha.setText("" + config[3]);

                if (Boolean.parseBoolean(config[4])) {
                    ChkUsarEscenaroPredefinido.setSelected(true);
                } else {
                    chkUsarEscenarioAleatorio.setSelected(true);
                }


                if (config[5].equals("0")) {
                    chkActivarRelentizacion.setSelected(false);
                    DesactivaSeleccionRelentizacion();
                } else {
                    chkActivarRelentizacion.setSelected(true);
                    ActivaSeleccionRelentizacion();
                }
                txtRiempoRelentizacion.setText(config[5]);

                txtTiempoGrabacion.setText("" + config[6]);

                txtTiempoGrabacionEstadisticas.setText(config[7]);
                txtSeed.setText(config[8]);

                 if (Boolean.parseBoolean(config[9])) {
                    ChkCrossValidation.setSelected(true);
                } else {
                    ChkCrossValidation.setSelected(false);
                }

            } catch (Exception e) {
                JDExcepcion jDExcepcion = new JDExcepcion();
                jDExcepcion.setPreferredSize(new Dimension(564, 230));
                jDExcepcion.pack();
                jDExcepcion.setLocationRelativeTo(this);
                jDExcepcion.setText(e.getMessage());
                jDExcepcion.setVisible(true);
            }


        }
        super.setVisible(visible);
    }

private void checked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checked
// TODO add your handling code here:
    if (chkActivarRelentizacion.isSelected()) {
        ActivaSeleccionRelentizacion();
    } else {
        DesactivaSeleccionRelentizacion();
    }
}//GEN-LAST:event_checked

private void sliderIzquierdaListener(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderIzquierdaListener
// TODO add your handling code here:
    if (((JSlider) (evt.getSource())).getValueIsAdjusting()) {
        lblIzquierda.setText("" + (double) ((JSlider) (evt.getSource())).getValue() / 100);
    }

}//GEN-LAST:event_sliderIzquierdaListener

private void DerechaStateChange(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_DerechaStateChange
// TODO add your handling code here:
    if (((JSlider) (evt.getSource())).getValueIsAdjusting()) {
        lblDerecha.setText("" + (double) ((JSlider) (evt.getSource())).getValue() / 100);
    }
}//GEN-LAST:event_DerechaStateChange

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:

    JFileChooser jfc = new JFileChooser();
    jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    if (jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
        txtRutaFicheros.setText(jfc.getSelectedFile().getAbsolutePath());
    }
}//GEN-LAST:event_jButton1ActionPerformed

private void jBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarActionPerformed
// TODO add your handling code here:
    //Grabar
    String[] config = new String[10];
    if (chkBayesNet.isSelected()) {
        config[0] = "bayesnet";
    } else {
        if (cHKNaiveBayes.isSelected()) {
            config[0] = "naivebayes";
        } else {
            if (cHKJ48.isSelected()) {
                config[0] = "j48";
            } else {
                if (cHKJ48Graft.isSelected()) {
                    config[0] = "j48graft";
                } else {
                    if (cHKNBTree.isSelected()) {
                        config[0] = "nbtree";
                    } else {
                        if (ChkBayedNetTAN.isSelected()) {
                            config[0] = "bayesnetTAN";
                        }
                    }
                }
            }
        }
    }

    config[1] = txtRutaFicheros.getText();
    config[2] = "" + sIzquierda.getValue();
    config[3] = "" + sDerecha.getValue();
    config[4] = "" + ChkUsarEscenaroPredefinido.isSelected();
    config[5] = "" + txtRiempoRelentizacion.getText();
    config[6] = "" + txtTiempoGrabacion.getText();
    config[7] = "" + txtTiempoGrabacionEstadisticas.getText();
    config[8] = "" + txtSeed.getText();
    config[9] = "" + ChkCrossValidation.isSelected();
    try {
        crtlApp.grabarConfiguracion(config);
        this.setVisible(false);
    } catch (Exception e) {
        JDExcepcion jDExcepcion = new JDExcepcion();
        jDExcepcion.setPreferredSize(new Dimension(564, 230));
        jDExcepcion.pack();
        jDExcepcion.setLocationRelativeTo(this);
        jDExcepcion.setText(e.getMessage());
        jDExcepcion.setVisible(true);
    }

}//GEN-LAST:event_jBAceptarActionPerformed
    private void ActivaSeleccionRelentizacion() {
        lblTiempoEnMs.setEnabled(true);
        lblTiempoEntrefps.setEnabled(true);
        txtRiempoRelentizacion.setEnabled(true);
    }

    private void DesactivaSeleccionRelentizacion() {
        lblTiempoEnMs.setEnabled(false);
        lblTiempoEntrefps.setEnabled(false);
        txtRiempoRelentizacion.setEnabled(false);
        txtRiempoRelentizacion.setText("0");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ChkBayedNetTAN;
    private javax.swing.JCheckBox ChkCrossValidation;
    private javax.swing.JCheckBox ChkUsarEscenaroPredefinido;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton cHKJ48;
    private javax.swing.JRadioButton cHKJ48Graft;
    private javax.swing.JRadioButton cHKNBTree;
    private javax.swing.JRadioButton cHKNaiveBayes;
    private javax.swing.JCheckBox chkActivarRelentizacion;
    private javax.swing.JRadioButton chkBayesNet;
    private javax.swing.JCheckBox chkUsarEscenarioAleatorio;
    private javax.swing.JButton jBAceptar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblDerecha;
    private javax.swing.JLabel lblIzquierda;
    private javax.swing.JLabel lblTiempoEnMs;
    private javax.swing.JLabel lblTiempoEntrefps;
    private JSlider sDerecha;
    private JSlider sIzquierda;
    private javax.swing.JTextField txtRiempoRelentizacion;
    private javax.swing.JTextField txtRutaFicheros;
    private javax.swing.JTextField txtSeed;
    private javax.swing.JTextField txtTiempoGrabacion;
    private javax.swing.JTextField txtTiempoGrabacionEstadisticas;
    // End of variables declaration//GEN-END:variables
}
